---
language: python
python: "3.11"

install:
  - pip install ansible ansible-lint
  - ansible --version

script:
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check
  - ansible-lint tasks/main.yml tasks/luks.yml tasks/lv_creation.yml

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
