---
- name: Partition disk and set LVM flag
  parted:
    device: "{{ disks.disk_name }}"
    label: gpt
    number: "{{ disks.pv_number }}"
    state: present
    fs_type: ext4
    flags: [lvm]
  no_log: false
  with_items: "{{ spec }}"
  loop_control:
    loop_var: disks

- name: Create volume groups
  lvg:
    vg: "{{ disks.vg_name }}"
    pvs: "{{ disks.vg_path }}"
  no_log: false
  with_items: "{{ spec }}"
  loop_control:
    loop_var: disks

- name: Create vault key directory
  file:
    state: directory
    path: "{{ disks.keys_path }}"
    owner: root
    group: root
    mode: "0700"
  no_log: false
  with_items: "{{ spec }}"
  loop_control:
    loop_var: disks

- name: Generate LUKS key file if not present
  command: >
    dd if=/dev/urandom
    of={{ disks.0.keys_path }}/{{ disks.1.lv_name }}
    bs=1024 count=4
  args:
    creates: "{{ disks.0.keys_path }}/{{ disks.1.lv_name }}"
  no_log: false
  with_subelements:
    - "{{ spec }}"
    - lv_specifications
  loop_control:
    loop_var: disks

- name: Set LUKS key file permissions
  file:
    state: file
    path: "{{ disks.0.keys_path }}/{{ disks.1.lv_name }}"
    owner: root
    group: root
    mode: "0400"
  no_log: false
  with_subelements:
    - "{{ spec }}"
    - lv_specifications
  loop_control:
    loop_var: disks

- name: Sync key files to remote key manager
  command: >
    rsync -avz
    -e "ssh -i {{ disks.key_storage.remote_key }} -p {{ disks.key_storage.remote_port }} -o StrictHostKeyChecking=no"
    {{ disks.keys_path }}/
    {{ disks.key_storage.remote_user }}@{{ disks.key_storage.remote_host }}:{{ disks.key_storage.remote_path }}/
  no_log: false
  with_items: "{{ spec }}"
  loop_control:
    loop_var: disks
  when: disks.key_storage.remote_storage | bool

- name: Create logical volumes and LUKS containers
  include_tasks: lv_creation.yml
  no_log: false
  with_subelements:
    - "{{ spec }}"
    - lv_specifications
  loop_control:
    loop_var: disks
