---
- name: Install LVM and LUKS packages
  become: true
  apt:
    name: "{{ lvm_packages }}"
    state: present
    update_cache: true
  when: lvm_install | bool

- name: Install Clevis packages
  become: true
  apt:
    name: "{{ clevis_packages }}"
    state: present
  when: clevis_install | bool

- name: Run LUKS provisioning tasks
  become: true
  ansible.builtin.import_tasks: luks.yml
  no_log: "{{ hide_logs }}"
